---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: comments-service
  namespace: dsn
spec:
  encryptedData:
    DATABASE_URL: AgApiOCT9WOyoUQ49DJ85kzYouM4gy2L1UxFIt99KlPU2PhNplej0Hh0lNIeAobxhrdQmVeROfXELpIb/BlGeFxQGPHZxgdj3qZs74JiRhb2A06YFpwyvSVIrPDNyfiBudxJ6e59IBKcGa99h+0uVqhyLYYo9Wx3aqTYsv9Fo73LzhXddvXHiMoeBE7gkidQKrKXOxWGnZGOl5VxHpg6Niz5t2U4ZdZT56zYz3hu0fb79oh3XtOd8/MpxKyxlmvvCACNsdPf3NRUf6oRRx6hJGefujCxEVnaEU9X+TrcJdCSt3vFXwJt75bXRNQEHtq2IIG2khrOlGiijaZnhgplfU6L+Fwy142vBMvt3Pwewo8EGsimjQLJzVTq3cfzmENriJjkni2QnBSLLUiMEE8p9Ulcpj3c1jsnVS+vx5U0TmQ2Tjy43IDnp3zAuzxVisK44UqeIsatX1LnVAdsIUMf4OGO2NQWPaRBMaEHbNo74PpqMPyqcpjtgx8U3ScCG59FapCNR7BJtl5DPWu/6gwp4PTminUKuJ1wMCWkk3BymDB+JuuN2IcoSHZM2+aogk4veBsCXJaFTZd8dhI1C4AbDVMUF6DPiOkHpTmlS7GNuzG6sRNKsbfzy46+sNgjCu4oiBy4RL8xpJ49kAlJZGlbj0FmxGLtMRmFTWjNE1l3c/sRQSAT8qSd3ctKs9ouWna2z+ptSB3/ivZgtIG14Is2BK1lH6WJ2j1ai5sZVffZ7wUny7CY9w/4H3Fu/rBiEzXYz8snCfKvp887MmdzhtxwYuO/ibBkddtvthcrF2xO6GeG88Hj6+OT7A+3cuW7XORB
  template:
    metadata:
      name: comments-service
      namespace: dsn
