---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: likes-service
  namespace: dsn
spec:
  encryptedData:
    DATABASE_URL: AgBA6HC4TKfJssIr3AxsI5wv0e+rtem85W1YnmTSno39pcaWfNWyVQeuY6UKJkytGH1DK/nD8UoPCQniEmX+DEZrQcUN2t221WTCpQUG4D2K6LJ7uulLMNw0W0Z6skkAT7bd0KbZ1Bir9yWflIq53iIIMavkfNlJ1WKw4nV6mcle5s9BXJ2jtzpR1jRxsFo8HZdGF7V8fDGwGHdSI7/EQtCRYy4r8aAOXpwVnKdPEL8QW7BDuGav78eopVuq+cEiEUehY72mXGsWfbeHIgV8y2Dlz6GoaRFEy2oF3OlHTksP2CdRr4mqGNTIumO5b/w2PZLF4Rmwq67DSoUBE7raW89aV6XdE1ZLoScNFijELEFkaI5r7nOxgtmrUGr6/3gJFh1BIkUgdEGwn1ibCF8Sk7ACWokaJ7+1knmLcmx4BGEQ6skW1TWDq1efPtGtBEN/t8xR1l8J99DAkNN82/e9JHZ/iO1GZRbz21ocpYqL5LZr0tWv+pbjYF+6qX6+G4xd1dbeTfdESqRtVastvNzNbVO2G6Gs4Ak3obcjVL8oK5CXhDepQHHXrbG5vj0IcLnQ1HCoWv+5YnJNi4U+f7equI2uRTztqHV2ROOvvojpJ6U7yljK5vvpy4TWoAMlmBbQsf7tc4ZjOD0U52OpKJwl3hJwP85mqbOeIYocAyRhTwiQSCH9tOwxkzpyitAO0zi8p3wOwPTkMpbz5qkwtAIypkPI2b4/V8Kp08acLcYlq0IGXGtcNW2BEDIIAxtoOS3a7BS1dzVaceKwLXamBdnudsDAVkw2mAvXbXSUt6AwhsthuT5EFWnzpUsB
  template:
    metadata:
      name: likes-service
      namespace: dsn
