---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: media-service
  namespace: dsn
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgAbT4XUpSHsQC9Ff2x2kBFluiR3y3sPYlsgAyDP3IX0D1YN4elIMEE0N33bMy3DDq7c0WphOnm01VTyEMYdcx2gKkuaxK5CCHlD9GUGX8z0LlVfluzgpJC9chIGBt3I265cy/SezJHQbbZXDl3zU67fQ4xBSuF7AHkGKEAlczmGkNAjxfbha/uab8XRRm03xXSZ5x44wt/7tis50mAqg1FlPMlkIdN9PNhuS+zZsIO5kBQb2ZOYRwMsJIQOVSF1EJE7BBJbR6UjXov9mFnMi/pTbdbegTr1ItNt4NLtSarLlSxwTV0it1ltwCwKN/Yw6S+KfilJBGZzNcGjTzEq2WwUDzXumQD+NxYNNk7kw2FmVTi+i5s4SWc7kO8305zcNcFB8O5HIdWGo2NrQArp13kPL3vboyFpjuQcxllNjl45A0mm4KwHSH53dQoVbB4lUKPPOZ7BLQdwADWKxPQ9JaWiZTtwokerAArE6muuZO9UPv5/ORIoyqWjqATagKNNMNTdfd3b1YhgPvC3eizT+UChKFLicdlie2uADDmfsO4Ps6toSXmTqK+8/0OnLLIvEjPknMykKmwWMOK36wnbhh/AOv2YU8IhqXYHBT6Zv+r+QgXBHB8Ecb/k7GIkZzHeOLWBvATiIdGbL/EGmhxAwdssIDFJY7vIvIyWD6YzLAEV+gbiinfiOdhA+ZVPDD2oCNQoEjyL3gLTzg0=
    MINIO_SECRET_KEY: AgATTpwbwjgk8CyezC1v0tt95pLAeN+fzfTyjiT2lysuz2JzBiw3zL2ATOy9C6zKJAGuxX/d3v85HJYdwUcE+ubIqro0teeHx9SnxzCGIJ6CsSXlEiV3qcZu4VLLfCsfp15ue521RtzffL8gReVRikmM1DlilFKtLJ0qWYXUSDD7nOdB5Uare53DVhWSiO1gYztmRs4nentm/qI9jg6rXs/FOvNNkxspYlkYuXGHlIdWAnGAXlR5LTYBbmAPrjSyaC8/GHNla0jyuuOA94z7B6VYJl6XBfIZ6nxRll5zJivQ61sDPMtyv1bGcbtFD+tZOwdebAYLivNe32JEo50td/vwv0Slf+gld14p0q92XxkelKuzPNdRSTABFf633/F3CaNaiIMn97ny3U/hVbjxL0ORi2VyzAgA1osvMCYdGv7Ee+4u0WB5h+VqwkMxdUWMsrF+2CNMGUz9Lnda4JNXAKK1EH5p166synAnDoRPM9r06fQuyGtQ3EVANtCPGithp3vYxv3Vgft8gb7HqOMxVJ6bFWzTID21nz4GZfFCFwPUbfKJwr5XNshM5Z6hsiH3Vm1lAP+0xS6RG9ZWsVx/0EPTSJ0o0el+A+4rPRBf9C+Rz+jS5es/WNf6SZHnX2u0AXZ7X7/O7NNnFzTvkkEEb+bBAgl2ttE0zz9o9IcagMbxUM0HOZjqmxK1gWNTEQVZMGPYo2paoWxApzgNlOK25E6vzAJjyi4wMQPjSUv+V3SlIg==
  template:
    metadata:
      name: media-service
      namespace: dsn
