---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: dsn
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAbLRUl8K+7A9Lr286ulYDz0aw1csDvElW/hqzlSNoaAaHx2MDaWASTMT5xQJx07ncyn6DkOeVAp6qBKo/K2LiW38kiDrx5+qC9q1Ojb2r+Rwb1ns3hzc/MQOr+m6TICVgrt5UmHEAOOAus5XB9xGmf6xjKvI4b4uxN3cqPeMMwA59J6XByERO+mGJIpHFFPNjpJ9Vfhs8WZu1osH5AbAezAMs80JoaNlGCIk2D7SEXeh1xOWV6hKXAWiOH4zfYR70iyQFtn8XHwOpZiin9+JQ1MNYA3eLtJkAVyqmUJcGE+9flaAglEPg3wTv+rZxYweuil02kKngshpGY+q/hUs7VBK9yxwfjgsMS18rl+YZO96WOR22VNr1N9RmJnTUxsL3+bSudKBmlDZeFMEZ/Ok8mnfgtx+l7Wo1xTuProqomf5/RnOj14EEzrd7Z9CJSzNJAumuaO2TAdSjIP4X/pXCzPpMjsgFJF25e9XTxyUlb8ufhDWy5sBoznXNCjEEQBogV7jyDZQ7oRUotIsinQyrWAJQMMCEotFRB3u3AV0WJE4UdWmaw6RWukVgYJYRADIlDMMlLHHn3Ae+lkwsWVJrK67RbxymmdtQ81wVNL7MGGNYtLCpmMKpiw8qEcxEpkYLcHf76ELno6O27J7S5Yf2HvQEDqebXUkm4R7PYd5wOyo3lpb7a7Ifx5ISh+4HJi2YgpRab2aOUnJYJKY0Cb9VEYRLmCWCKm2VeG60p0tCV1g==
    MINIO_ROOT_USER: AgBI0+4U+oNnpH59U/yQIztCrW/kPXKicEywomrpOdP5pojTm293FATTIcLNA1ple/JkmiWRXluB1hNGgl6TgHsr3A0WXzWhMaAlBUCSCczYbYwuiKns/J/txGrVJNWBLBQfny7TWR1xTss6PUc4dFFMZflhXTIUIVcYZFqZhaRs71ymlGyO19tsDR76bUeC7vBi/9TdnQMaL1uN/Uj+n3DNoAz4XVopWlnIMMkv10DjhnqZB76kxM/lgbFdArGMurqfdz2JHbDZ3xwjZvgpU9pse16oURfW3KnIgLLdgkM2OG7VSqLic4GdjtlGNjej983c4N2+I+BuhjeRFQRtRrSyZAhT2bTxV6BGKNQFOKxxeGSrux2A/nAtjT50LfimJS5AgvRg4A42IXeYsjY3X2A17ujsH9CHmaE/TDs57szcMSvoRF52Tl67ws2FnTM+H6c70jZ6IE3VnsCZ/9O/+7wTAJclxMXHZXhJVdiAd82lfaFBgy0k04+2ZJq3J1IBaR0zlUSkVN5hLJz6n18JHLBmT1gaj3PiAqeO8/UIf18MTua9XMmDRo34HtW5FMxTgPkcbbNrzSmNK8oxmZZF4ww/RxAxI3LTYuWADIFNrJfrHeM3Rl8IxOJf4P9UT4zFC8SKfyEwXPUJeUJePKw4fWnNv4tMiqlkSEGXg13WoN1WlhV8NTiKbPLIg9XaU7cLNACKUpTchnTgfI4=
  template:
    metadata:
      name: minio-credentials
      namespace: dsn
