---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notification-service
  namespace: dsn
spec:
  encryptedData:
    DATABASE_URL: AgCzDP4AxB3GZGj55DrhGhywXI2oReme2FQXnSALxzwUdf1gwhGNkikYy/hM9lXroduiZ9iW5u4c1m5yqH2Zk7xrgg+uvxPTnjAAhWroTmfY2WJMen/AnBZ8NJQN3mqfRFyTfOLgfxrp4GYEfaxL1OHnyLPxwxd9hX6m7p/oPAb4gT9i7GUYoFWY2v23RMV46KBzZAWO8kDAi+jV2Vc4DIG08VUI0f5i2+JOmaLJvbw+8q6sVVtHHk8xpNW/7grzd8uc8AMAARXFxaTVsvFHEO75xeTVkONiyK+31B3Q0B1IcLS3dBVmEpBB8KAERFHzMT/KXsydajvPENdmFdFK2iJBeFuDeC6FGLHY2Sj6N4pNrfk+iSLM2wd/ByYd/JJ7HmghGGPWDq6Wcpzduzg8De5WolMI02Q7Mqo6ALfHArkTxCh2rNU51Ob6ytRb2NAl+P5dfHpMnYDWI8PfUxeus/adlTceRXFhKT0eVUgOuhUGzMECviVTELlFYz+mY2aBSFp9T6r2JtEew6DvXy4EzPKWmIOGm53pojvDfipzzCIDSdwLHrHfWGhTxwTIU26iyi+Wx2O/Aw2dW0+HnocdBKaSGlc5f7Cp/UDKYKzmFOeB7ipQIz2vRiICZPG7/q206Jiy+OG5Vdx9CLLFJLVMb3PonCRduxroE5U51J99fBcuJwRSl+ZPNf2ZUxVUE0nReA7Rih8v5cTPq8k7lx3D63IK59tLGC0NylTgPAw/fExJScUCSjg9/zMmntFjsyfEpkyciWOHpleEbul02BKeJzgNWZiUKVqaHfp6b+wkQgyNr7CDIzv/+Lg0kNX3e336GkNKZ2jefqlCjg==
  template:
    metadata:
      name: notification-service
      namespace: dsn
