---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: dsn
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC6apOYSw51z5fnh6IXuIHp4HxFVTJ5iDKUFWF/IFNvKudNXpXblv4LKdZURUaDfIjokjtP6RLOc8VmkOeMmNPmw3wgCfVLEpu0BfnrFu/qbKbgmR6+sDPsJo4SpIQmBOY3zfzq39khPD/8iFIieCbAOvq4xeCeeAKJuxA8qv1cvQicKVOPY+BQcfRB0wQAg4Kkr9xscoAhUx0PurpKXRhQJM12k43gy8snzaCnCWW+5gzaEihaVrRPSU3QRXdnJMWDzYvAB1evkJiFOEfI7TZbDM2QGoVy0W2ecSLy2Rlxn/Eq6BrTJcdnWE3t+tG02U3onZ4EevVoAS9dwNlxHBwLwK+vy31cDSn+FkvyZHb6/yTz/AkU3dgvOV+8Zyw02f0kC8oMQSbrig3qIwuw2zG8koE0O1i/N1PQlkO9vM2BhXjIIZtxy3wmMdpqBoHIsn4zobcuJPVfYURx9WNEupGp/jPpWQfY9Z13rY2QgXKtG9Sm3QMru9OrnwLNB4szX81rL5IR0E0R6Bw1JdCwvmNfmhbKLgdboGnvzId5zN8tve+bvf3DajFBfg3O46cm2XZlN53U/7quOMP1E7N7x95lCsd7kOjkpbw/bf4YT36byWF9yBl8lA/3DNZLQkJz1wmkDQogdB3wjUJTb4kCVTgpFlXYHjuN2L0/Ze5y9pxL2GnqjolOj3ppkkq7ubEUrr5ZQB+VcCpUfr5hC32uW6uhk5rLX1+ql6SWdbZKKImUAw==
  template:
    metadata:
      name: postgres-credentials
      namespace: dsn
