---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: users-service
  namespace: dsn
spec:
  encryptedData:
    DATABASE_URL: AgCuWM3ZNifgBXO2pI7TC9Waqn1J9eYirkm1oZxPMw0IVNw3xBO5j/42jn+waQBbtmF3zZAaeS6nrsJzZFE/7Glesd2jhtp7lL8YpAKnI7E8A1T7wrf+8D1w/JozdUnxg/aP92OTZko4U6ZL+YREdVjuMWg33jeXuzOXOfx7b/8ZfUhYZnIzBiYLy+RGmMOlTrn4orH1tqToZnKlt/BxRJH7sIXLpbgHVYYOidYTc/j1mOOxii10sDyseT1M1YvzyPiKDzNDSkMPBUKMDClRwrcc5o7kOrJar6NQUGrTkDIQy7nCTzoXhQ1n1TmWFYtUhA6joD18S+/P7kF732sJ0OfY2L89aNdaLaYYlERxO7aPb+q6FSYxEUVnNrtimORzQUBfRkwSsIZyPWr3m/C9Y5SBFCrgcsrWNSxBH7cwFkow+XW3zJZMfsiXZwoHof6dbf6XR6G/PrCtTXk+1PEfaXgcMfKqhs12tHMtKOOsUhGUaZ2MsfNbCSPxNP9sS0+qKBvyDYDtezQHBizNaBVbFobXKYiR5Vf1RL8FB099yhgqODMNDG1ALi+0PF0HiIJTresQ9Aos5S+SsAdm7KJ8/q+9rWYO2QMS3JfqUL5avF8fpYCgxaOgU6lj49Ivf0N1vudiqBEL4jkdjtcx5pos2i4U74EpoamhzY9gH0UNrDY9mF4ojwsOAeTt0+ymJckCij4/pHzQf2y1Bhugyhs6QtehF4cunmK/Fr8ChhUiMtt3fPYP1EGHTXSf720MZNUzghTAC+6uKCOqplKyLqGGFXa2yUlNkSkeG2W4tp+l1BvkQqqR7pBlxjK2
  template:
    metadata:
      name: users-service
      namespace: dsn
